vote_category_id:
  type: string
  default: "7"
  description: 
    en: 'Category ID to select the votes from.'
vote_tag_name:
  type: string
  default: "on-roadmap,under-consideration"
  description: 
    en: 'Comma separated tag names to select the votes from.'


